# Dependabot Auto-merge Configuration
# This file defines rules for safely auto-merging dependency updates

name: Auto-merge Dependabot PRs
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: |
          # Auto-merge rules:
          # 1. Minor and patch updates for most dependencies
          # 2. All GitHub Actions updates (they're generally safe)
          # 3. Security updates (always safe to merge)
          
          PR_TITLE="${{ github.event.pull_request.title }}"
          
          # Check if this is a safe update to auto-merge
          if [[ "$PR_TITLE" =~ "Bump actions/" ]] || \
             [[ "$PR_TITLE" =~ "security" ]] || \
             [[ "$PR_TITLE" =~ "patch" ]] || \
             [[ "$PR_TITLE" =~ "minor" ]]; then
            
            echo "This PR is eligible for auto-merge"
            gh pr merge --auto --squash ${{ github.event.pull_request.number }}
          else
            echo "This PR requires manual review"
            gh pr comment ${{ github.event.pull_request.number }} --body "🤖 This dependency update requires manual review before merging."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add auto-merge label
        if: contains(github.event.pull_request.title, 'Bump actions/') || contains(github.event.pull_request.title, 'security')
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "automerge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}