version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Gameaday"
    assignees:
      - "Gameaday"
    labels:
      - "dependency-update"
    commit-message:
      prefix: "⬆️"
      include: "scope"

  # Enable version updates for Gradle dependencies (if we migrate to Gradle)
  - package-ecosystem: "gradle"
    directory: "/Don't look back"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Gameaday"
    assignees:
      - "Gameaday"
    labels:
      - "dependency-update"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    ignore:
      # Ignore major version updates for LWJGL (requires manual testing)
      - dependency-name: "org.lwjgl:*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for Maven dependencies (if we migrate to Maven)
  - package-ecosystem: "maven"
    directory: "/Don't look back"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Gameaday"
    assignees:
      - "Gameaday"
    labels:
      - "dependency-update"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    ignore:
      # Ignore major version updates for LWJGL (requires manual testing)
      - dependency-name: "org.lwjgl:*"
        update-types: ["version-update:semver-major"]