---
version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Gameaday"
    assignees:
      - "Gameaday"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "⬆️(deps)"
      include: "scope"
    groups:
      actions:
        patterns:
          - "actions/*"
          - "github/*"

  # Gradle dependencies (primary build system)
  - package-ecosystem: "gradle"
    directory: "/Don't look back"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Gameaday"
    assignees:
      - "Gameaday"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "⬆️(deps)"
      include: "scope"
    groups:
      # Group LWJGL dependencies together since they should be updated in sync
      lwjgl:
        patterns:
          - "org.lwjgl:*"
        update-types:
          - "minor"
          - "patch"
      # Group testing dependencies
      testing:
        patterns:
          - "org.junit.*:*"
          - "*junit*"
        update-types:
          - "minor"
          - "patch"
      # Group physics engine dependencies
      physics:
        patterns:
          - "org.jbox2d:*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Ignore major version updates for LWJGL (breaking changes require test)
      - dependency-name: "org.lwjgl:*"
        update-types: ["version-update:semver-major"]
      # Ignore major JUnit updates (may require test refactoring)
      - dependency-name: "org.junit.*:*"
        update-types: ["version-update:semver-major"]
    # Enable vulnerability alerts and auto-security updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Version catalog support for Gradle
    versioning-strategy: increase
