name: Release Pipeline

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  build-release:
    runs-on: ubuntu-latest
    name: Build Release Artifacts
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    - name: Build release with native packages
      run: |
        cd "Don't look back"
        # Build everything including native packages and documentation
        gradle buildAll --no-daemon
        
        # Build platform-specific installers  
        gradle buildInstallers --no-daemon || echo "Some installer types may not be available"
        
    - name: Create comprehensive release packages
      run: |
        cd "Don't look back"
        VERSION="${{ github.event.inputs.version || github.event.release.tag_name }}"
        
        # Create release directory
        mkdir -p release
        
        # Copy main JAR (fat JAR from Gradle build)
        cp app/build/libs/DontLookBack-1.0-fat.jar release/
        
        # Copy regular JAR as backup
        cp app/build/libs/app.jar release/ 2>/dev/null || echo "Regular JAR not available"
        
        # Copy dependencies (LWJGL natives are now embedded in fat JAR)
        echo "Modern build includes all dependencies in fat JAR"
        
        # Copy resources
        cp -r res release/ 2>/dev/null || echo "Resources not available"
        
        # Copy documentation (from Gradle build)
        cp -r app/build/docs/javadoc release/ 2>/dev/null || echo "Javadoc not available"
        
        # Create startup scripts
        cat > release/run.sh << 'EOF'
        #!/bin/bash
        # Don't Look Back - Linux/Mac startup script
        # Modern version with self-contained JAR
        
        # Run the game (fat JAR includes all dependencies)
        java -jar DontLookBack-1.0-fat.jar
        EOF
        
        cat > release/run.bat << 'EOF'
        @echo off
        REM Don't Look Back - Windows startup script
        REM Modern version with self-contained JAR
        
        REM Run the game (fat JAR includes all dependencies)
        java -jar DontLookBack-1.0-fat.jar
        
        pause
        EOF
        
        # Make shell script executable
        chmod +x release/run.sh
        
        # Create release info
        cat > release/RELEASE_INFO.txt << EOF
        Don't Look Back - Release ${VERSION}
        ===================================
        
        Release Information:
        - Version: ${VERSION}
        - Build Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        - Git Commit: ${{ github.sha }}
        - Build Number: ${{ github.run_number }}
        - Build System: Gradle with modern dependencies
        
        System Requirements:
        - Java 17 or higher
        - OpenGL 2.1 compatible graphics card
        - 512MB RAM minimum
        - 100MB disk space
        
        Installation:
        1. Extract all files to a directory
        2. Run run.sh (Linux/Mac) or run.bat (Windows)
        
        Files:
        - DontLookBack-1.0-fat.jar - Main game executable (self-contained)
        - app.jar - Regular JAR file (backup)
        - res/ - Game resources and assets
        - javadoc/ - API documentation
        - run.sh - Linux/Mac startup script
        - run.bat - Windows startup script
        
        Technical Notes:
        - Uses modern LWJGL 3.3.4 with embedded native libraries
        - JBox2D 2.2.1.1 physics engine included
        - All dependencies bundled in fat JAR
        
        For more information, visit: https://github.com/crnlabs/DLB
        EOF
        
        # Create platform-specific packages
        
        # Windows package
        zip -r "DontLookBack-${VERSION}-Windows.zip" release/
        
        # Linux package  
        tar -czf "DontLookBack-${VERSION}-Linux.tar.gz" release/
        
        # Cross-platform package
        zip -r "DontLookBack-${VERSION}-CrossPlatform.zip" release/
        
    - name: Upload Windows Release
      uses: actions/upload-artifact@v4
      with:
        name: dont-look-back-windows-${{ github.event.inputs.version || github.event.release.tag_name }}
        path: "Don't look back/DontLookBack-*-Windows.zip"
        
    - name: Upload Linux Release
      uses: actions/upload-artifact@v4
      with:
        name: dont-look-back-linux-${{ github.event.inputs.version || github.event.release.tag_name }}
        path: "Don't look back/DontLookBack-*-Linux.tar.gz"
        
    - name: Upload Cross-Platform Release
      uses: actions/upload-artifact@v4
      with:
        name: dont-look-back-crossplatform-${{ github.event.inputs.version || github.event.release.tag_name }}
        path: "Don't look back/DontLookBack-*-CrossPlatform.zip"
        
    - name: Get current date
      if: github.event_name == 'workflow_dispatch'
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - name: Create GitHub Release (if manual trigger)
      if: github.event_name == 'workflow_dispatch'
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version || '1.0.0' }}
        name: "Don't Look Back v${{ github.event.inputs.version || '1.0.0' }}"
        body: |
          ## Don't Look Back v${{ github.event.inputs.version || '1.0.0' }}
          
          **Release Date:** ${{ steps.date.outputs.date }}
          **Commit:** ${{ github.sha }}
          **Build:** ${{ github.run_number }}
          
          ### 🎮 Game Features
          - Horror survival gameplay with "don't look back" mechanics
          - Modern LWJGL 3.3.4 graphics engine with OpenGL support
          - JBox2D physics simulation
          - Cross-platform compatibility (Windows, Linux, macOS)
          
          ### 📦 Downloads
          - **Windows**: `DontLookBack-*-Windows.zip` - Windows-optimized package
          - **Linux**: `DontLookBack-*-Linux.tar.gz` - Linux package with shell scripts
          - **Cross-Platform**: `DontLookBack-*-CrossPlatform.zip` - Universal Java package
          
          ### 🔧 System Requirements
          - Java 17 or higher
          - OpenGL 2.1 compatible graphics card
          - 512MB RAM minimum
          - 100MB disk space
          
          ### 🚀 Quick Start
          1. Download the appropriate package for your platform
          2. Extract all files to a directory
          3. Run `run.sh` (Linux/Mac) or `run.bat` (Windows)
          4. Alternatively: `java -jar DontLookBack-1.0-fat.jar`
          
          For more information, visit: https://github.com/crnlabs/DLB
        draft: false
        prerelease: false
        files: |
          Don't look back/DontLookBack-*-Windows.zip
          Don't look back/DontLookBack-*-Linux.tar.gz
          Don't look back/DontLookBack-*-CrossPlatform.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Attach to Existing GitHub Release  
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Don't look back/DontLookBack-*-Windows.zip
          Don't look back/DontLookBack-*-Linux.tar.gz
          Don't look back/DontLookBack-*-CrossPlatform.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}