name: Release Pipeline

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  build-release:
    runs-on: ubuntu-latest
    name: Build Release Artifacts
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install Ant
      run: |
        sudo apt-get update
        sudo apt-get install -y ant
        
    - name: Build release
      run: |
        cd "Don't look back"
        ant clean compile jar javadoc
        
    - name: Create release package
      run: |
        cd "Don't look back"
        VERSION="${{ github.event.inputs.version || github.event.release.tag_name }}"
        
        # Create release directory
        mkdir -p release
        
        # Copy main JAR
        cp dist/*.jar release/
        
        # Copy dependencies
        mkdir -p release/lib
        cp -r ../lwjgl release/lib/ 2>/dev/null || echo "LWJGL not available"
        
        # Copy resources
        cp -r res release/ 2>/dev/null || echo "Resources not available"
        
        # Copy documentation
        cp -r dist/javadoc release/ 2>/dev/null || echo "Javadoc not available"
        
        # Create startup scripts
        cat > release/run.sh << 'EOF'
        #!/bin/bash
        # Don't Look Back - Linux/Mac startup script
        
        # Detect platform
        PLATFORM=""
        case "$(uname -s)" in
            Linux*)     PLATFORM="linux";;
            Darwin*)    PLATFORM="macosx";;
            *)          echo "Unsupported platform"; exit 1;;
        esac
        
        # Set library path
        NATIVE_PATH="lib/lwjgl/lwjgl-2.9.1/native/$PLATFORM"
        
        # Run the game
        java -Djava.library.path="$NATIVE_PATH" -jar Don_t_look_back.jar
        EOF
        
        cat > release/run.bat << 'EOF'
        @echo off
        REM Don't Look Back - Windows startup script
        
        REM Set library path for Windows
        set NATIVE_PATH=lib\lwjgl\lwjgl-2.9.1\native\windows
        
        REM Run the game
        java -Djava.library.path=%NATIVE_PATH% -jar Don_t_look_back.jar
        
        pause
        EOF
        
        # Make shell script executable
        chmod +x release/run.sh
        
        # Create release info
        cat > release/RELEASE_INFO.txt << EOF
        Don't Look Back - Release ${VERSION}
        ===================================
        
        Release Information:
        - Version: ${VERSION}
        - Build Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        - Git Commit: ${{ github.sha }}
        - Build Number: ${{ github.run_number }}
        
        System Requirements:
        - Java 17 or higher
        - OpenGL 2.1 compatible graphics card
        - 512MB RAM minimum
        - 100MB disk space
        
        Installation:
        1. Extract all files to a directory
        2. Run run.sh (Linux/Mac) or run.bat (Windows)
        
        Files:
        - Don_t_look_back.jar - Main game executable
        - lib/ - Required libraries and native files
        - res/ - Game resources and assets
        - javadoc/ - API documentation
        - run.sh - Linux/Mac startup script
        - run.bat - Windows startup script
        
        For more information, visit: https://github.com/crnlabs/DLB
        EOF
        
        # Create platform-specific packages
        
        # Windows package
        zip -r "DontLookBack-${VERSION}-Windows.zip" release/
        
        # Linux package  
        tar -czf "DontLookBack-${VERSION}-Linux.tar.gz" release/
        
        # Cross-platform package
        zip -r "DontLookBack-${VERSION}-CrossPlatform.zip" release/
        
    - name: Upload Windows Release
      uses: actions/upload-artifact@v4
      with:
        name: dont-look-back-windows-${{ github.event.inputs.version || github.event.release.tag_name }}
        path: "Don't look back/DontLookBack-*-Windows.zip"
        
    - name: Upload Linux Release
      uses: actions/upload-artifact@v4
      with:
        name: dont-look-back-linux-${{ github.event.inputs.version || github.event.release.tag_name }}
        path: "Don't look back/DontLookBack-*-Linux.tar.gz"
        
    - name: Upload Cross-Platform Release
      uses: actions/upload-artifact@v4
      with:
        name: dont-look-back-crossplatform-${{ github.event.inputs.version || github.event.release.tag_name }}
        path: "Don't look back/DontLookBack-*-CrossPlatform.zip"
        
    - name: Attach to GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Don't look back/DontLookBack-*-Windows.zip
          Don't look back/DontLookBack-*-Linux.tar.gz
          Don't look back/DontLookBack-*-CrossPlatform.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}